language: python
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      language: generic
      env: TRAVIS_OS_NAME=osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade python; fi
cache: pip
install:
  - pip3 install -r requirements.txt
before_script:
  - export PATH=$PATH:$(pwd)  
  - export PYTHONPATH=$PYTHONPATH:$(pwd)  
script:
  - coverage run --source=scripts setup.py test
after_success:
  - coveralls
